// DemoInterp.cxx
// Demonstrates 4 interpolation use-cases using OCCT geometry classes.
// Each demo writes input and result to separate OBJ files for visualization.
//
// Demos:
//   1. Curve interpolation through 3D points (no tangents)
//   2. Curve interpolation with prescribed end tangents
//   3. Curve interpolation with per-point tangents
//   4. Surface interpolation through a grid of (uv, xyz) data

#include <NCollection_Array1.hxx>
#include <NCollection_Array2.hxx>
#include <NCollection_HArray1.hxx>
#include <GeomAPI_Interpolate.hxx>
#include <Geom_BSplineCurve.hxx>
#include <GeomAPI_PointsToBSplineSurface.hxx>
#include <Geom_BSplineSurface.hxx>
#include <gp_Pnt.hxx>
#include <gp_Vec.hxx>
#include <iostream>
#include <fstream>
#include <cmath>
#include <vector>
#include <string>

// ===========================================================================
// OBJ output helpers
// ===========================================================================

struct ObjFile {
  std::ofstream f;
  int vcount = 0;

  ObjFile(const std::string& path) : f(path) {
    f << "# Generated by DemoInterp\n";
  }
  ~ObjFile() { f.close(); }

  void group(const char* name) { f << "g " << name << "\n"; }

  int vertex(const gp_Pnt& p) {
    f << "v " << p.X() << " " << p.Y() << " " << p.Z() << "\n";
    return ++vcount;
  }

  // Write a point cloud
  void writePoints(const std::vector<gp_Pnt>& pts) {
    int base = vcount;
    for (auto& p : pts) vertex(p);
    for (int i = 0; i < (int)pts.size(); ++i)
      f << "p " << (base + i + 1) << "\n";
  }

  // Write tangent arrows as short line segments (2-vertex per line)
  void writeTangentArrows(const std::vector<gp_Pnt>& pts,
                          const std::vector<gp_Vec>& tangs,
                          double scale = 0.15) {
    for (int i = 0; i < (int)pts.size(); ++i) {
      int v1 = vertex(pts[i]);
      gp_Pnt tip(pts[i].X() + tangs[i].X() * scale,
                 pts[i].Y() + tangs[i].Y() * scale,
                 pts[i].Z() + tangs[i].Z() * scale);
      int v2 = vertex(tip);
      f << "l " << v1 << " " << v2 << "\n";
    }
  }

  // Write a polyline as consecutive 2-vertex line segments
  void writePolyline(const std::vector<gp_Pnt>& pts) {
    if (pts.size() < 2) return;
    int base = vcount;
    for (auto& p : pts) vertex(p);
    for (int i = 0; i < (int)pts.size() - 1; ++i)
      f << "l " << (base + i + 1) << " " << (base + i + 2) << "\n";
  }

  // Write BSpline curve control points and control polygon
  void writeCtrlPoly(const occ::handle<Geom_BSplineCurve>& C) {
    if (C.IsNull()) return;
    int nP = C->NbPoles();
    // control points as point cloud
    group("ctrl_points");
    int base = vcount;
    for (int i = 1; i <= nP; ++i) vertex(C->Pole(i));
    for (int i = 0; i < nP; ++i)
      f << "p " << (base + i + 1) << "\n";
    // control polygon as 2-vertex line segments
    group("ctrl_polygon");
    for (int i = 0; i < nP - 1; ++i)
      f << "l " << (base + i + 1) << " " << (base + i + 2) << "\n";
  }

  // Write BSpline surface control points and control net
  void writeCtrlNet(const occ::handle<Geom_BSplineSurface>& S) {
    if (S.IsNull()) return;
    int nU = S->NbUPoles(), nV = S->NbVPoles();
    // control points
    group("ctrl_points");
    int base = vcount;
    for (int i = 1; i <= nU; ++i)
      for (int j = 1; j <= nV; ++j)
        vertex(S->Pole(i, j));
    for (int i = 0; i < nU * nV; ++i)
      f << "p " << (base + i + 1) << "\n";
    // control net: U-direction lines
    group("ctrl_net_u");
    for (int i = 0; i < nU; ++i)
      for (int j = 0; j < nV - 1; ++j) {
        int v0 = base + i * nV + j + 1;
        f << "l " << v0 << " " << (v0 + 1) << "\n";
      }
    // control net: V-direction lines
    group("ctrl_net_v");
    for (int j = 0; j < nV; ++j)
      for (int i = 0; i < nU - 1; ++i) {
        int v0 = base + i * nV + j + 1;
        int v1 = base + (i + 1) * nV + j + 1;
        f << "l " << v0 << " " << v1 << "\n";
      }
  }

  // Sample a BSpline curve and write as 2-vertex line segments
  void writeCurve(const occ::handle<Geom_BSplineCurve>& C, int nSamples = 100) {
    if (C.IsNull()) return;
    double u0 = C->FirstParameter(), u1 = C->LastParameter();
    std::vector<gp_Pnt> pts;
    for (int i = 0; i <= nSamples; ++i) {
      double u = u0 + (u1 - u0) * i / nSamples;
      gp_Pnt p;
      C->D0(u, p);
      pts.push_back(p);
    }
    writePolyline(pts);
  }

  // Sample a BSpline surface and write as triangle mesh
  void writeSurface(const occ::handle<Geom_BSplineSurface>& S,
                    int nu = 40, int nv = 40) {
    if (S.IsNull()) return;
    double u0 = S->UKnot(1), u1 = S->UKnot(S->NbUKnots());
    double v0 = S->VKnot(1), v1 = S->VKnot(S->NbVKnots());
    int base = vcount;
    for (int i = 0; i <= nu; ++i) {
      double u = u0 + (u1 - u0) * i / nu;
      for (int j = 0; j <= nv; ++j) {
        double v = v0 + (v1 - v0) * j / nv;
        gp_Pnt p;
        S->D0(u, v, p);
        vertex(p);
      }
    }
    for (int i = 0; i < nu; ++i) {
      for (int j = 0; j < nv; ++j) {
        int v00 = base + i * (nv + 1) + j + 1;
        int v10 = base + (i + 1) * (nv + 1) + j + 1;
        int v01 = v00 + 1;
        int v11 = v10 + 1;
        f << "f " << v00 << " " << v10 << " " << v11 << "\n";
        f << "f " << v00 << " " << v11 << " " << v01 << "\n";
      }
    }
  }
};

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------
static void PrintCurveInfo(const occ::handle<Geom_BSplineCurve>& C, const char* label)
{
  if (C.IsNull()) { std::cout << label << ": FAILED (null result)\n"; return; }
  std::cout << label
            << ": degree=" << C->Degree()
            << "  nbPoles=" << C->NbPoles()
            << "  nbKnots=" << C->NbKnots() << "\n";
}

static void PrintSurfaceInfo(const occ::handle<Geom_BSplineSurface>& S, const char* label)
{
  if (S.IsNull()) { std::cout << label << ": FAILED (null result)\n"; return; }
  std::cout << label
            << ": degreeU=" << S->UDegree()
            << "  degreeV=" << S->VDegree()
            << "  nbPolesU=" << S->NbUPoles()
            << "  nbPolesV=" << S->NbVPoles() << "\n";
}

// ===========================================================================
// Demo 1: Curve interpolation through points (no derivative constraints)
// ===========================================================================
static void Demo1_CurveInterpPoints()
{
  const int N = 10;
  occ::handle<NCollection_HArray1<gp_Pnt>> hPts = new NCollection_HArray1<gp_Pnt>(1, N);
  std::vector<gp_Pnt> inputPts(N);
  for (int i = 1; i <= N; ++i) {
    double t = (i - 1) * 4.0 * M_PI / (N - 1);
    gp_Pnt p(std::cos(t), std::sin(t), t / 5.0);
    hPts->SetValue(i, p);
    inputPts[i - 1] = p;
  }

  GeomAPI_Interpolate interp(hPts, /*periodic=*/false, /*tol=*/1e-6);
  interp.Perform();

  occ::handle<Geom_BSplineCurve> curve = interp.Curve();
  PrintCurveInfo(curve, "Demo1 (point-only interp)");
  std::cout << "  (exact interpolation guaranteed by construction)\n";

  { ObjFile obj("demo1_input.obj");  obj.group("points");       obj.writePoints(inputPts); }
  { ObjFile obj("demo1_output.obj"); obj.group("result_curve"); obj.writeCurve(curve); }
  { ObjFile obj("demo1_ctrl.obj");   obj.writeCtrlPoly(curve); }
  std::cout << "  -> demo1_input.obj, demo1_output.obj, demo1_ctrl.obj\n";
}

// ===========================================================================
// Demo 2: Curve interpolation with prescribed end tangents
// ===========================================================================
static void Demo2_CurveInterpEndTangents()
{
  const int N = 20;
  occ::handle<NCollection_HArray1<gp_Pnt>> hPts = new NCollection_HArray1<gp_Pnt>(1, N);
  std::vector<gp_Pnt> inputPts(N);
  for (int i = 1; i <= N; ++i) {
    double t = (i - 1) * 4.0 * M_PI / (N - 1);
    gp_Pnt p(std::cos(t), std::sin(t), t / 5.0);
    hPts->SetValue(i, p);
    inputPts[i - 1] = p;
  }

  double t0 = 0.0, tN = 4.0 * M_PI;
  gp_Vec tangFirst(-std::sin(t0), std::cos(t0), 0.2);
  gp_Vec tangLast (-std::sin(tN), std::cos(tN), 0.2);
  // Normalize to unit direction — Load(Scale=true) will rescale to match
  // the chord-length parameterization. Without this, the analytic magnitude
  // causes huge overshoot.
  tangFirst.Normalize();
  tangLast.Normalize();

  GeomAPI_Interpolate interp(hPts, /*periodic=*/false, /*tol=*/1e-6);
  interp.Load(tangFirst, tangLast, /*Scale=*/false);
  interp.Perform();

  occ::handle<Geom_BSplineCurve> curve = interp.Curve();
  PrintCurveInfo(curve, "Demo2 (end-tangent interp)");
  std::cout << "  startTangent=(" << tangFirst.X() << ", "
            << tangFirst.Y() << ", " << tangFirst.Z() << ")\n";
  std::cout << "  endTangent  =(" << tangLast.X()  << ", "
            << tangLast.Y()  << ", " << tangLast.Z()  << ")\n";

  // Verify endpoints
  if (!curve.IsNull()) {
    gp_Pnt p0, p1;
    curve->D0(curve->FirstParameter(), p0);
    curve->D0(curve->LastParameter(),  p1);
    std::cout << "  curveStart=(" << p0.X() << ", " << p0.Y() << ", " << p0.Z() << ")"
              << "  inputFirst=(" << inputPts.front().X() << ", " << inputPts.front().Y() << ", " << inputPts.front().Z() << ")\n";
    std::cout << "  curveEnd  =(" << p1.X() << ", " << p1.Y() << ", " << p1.Z() << ")"
              << "  inputLast =(" << inputPts.back().X()  << ", " << inputPts.back().Y()  << ", " << inputPts.back().Z()  << ")\n";
  }

  {
    ObjFile obj("demo2_input.obj");
    obj.group("points");
    obj.writePoints(inputPts);
    obj.group("end_tangents");
    std::vector<gp_Pnt> endPts = { inputPts.front(), inputPts.back() };
    std::vector<gp_Vec> endTangs = { tangFirst, tangLast };
    obj.writeTangentArrows(endPts, endTangs);
  }
  { ObjFile obj("demo2_output.obj"); obj.group("result_curve"); obj.writeCurve(curve, 500); }
  { ObjFile obj("demo2_ctrl.obj");   obj.writeCtrlPoly(curve); }
  std::cout << "  -> demo2_input.obj, demo2_output.obj, demo2_ctrl.obj\n";
}

// ===========================================================================
// Demo 3: Curve interpolation with per-point tangents
// ===========================================================================
static void Demo3_CurveInterpAllTangents()
{
  const int N = 8;
  occ::handle<NCollection_HArray1<gp_Pnt>> hPts = new NCollection_HArray1<gp_Pnt>(1, N);
  NCollection_Array1<gp_Vec>               tangs(1, N);
  occ::handle<NCollection_HArray1<bool>>   flags = new NCollection_HArray1<bool>(1, N);

  std::vector<gp_Pnt> inputPts(N);
  std::vector<gp_Vec> inputTangs(N);
  for (int i = 1; i <= N; ++i) {
    double t = (i - 1) * 4.0 * M_PI / (N - 1);
    gp_Pnt p(std::cos(t), std::sin(t), t / 5.0);
    gp_Vec v(-std::sin(t), std::cos(t), 0.2);
    hPts->SetValue(i, p);
    tangs(i) = v;
    flags->SetValue(i, true);
    inputPts[i - 1] = p;
    inputTangs[i - 1] = v;
  }

  GeomAPI_Interpolate interp(hPts, /*periodic=*/false, /*tol=*/1e-6);
  interp.Load(tangs, flags);
  interp.Perform();

  occ::handle<Geom_BSplineCurve> curve = interp.Curve();
  PrintCurveInfo(curve, "Demo3 (per-point tangent interp)");

  {
    ObjFile obj("demo3_input.obj");
    obj.group("points");
    obj.writePoints(inputPts);
    obj.group("tangents");
    obj.writeTangentArrows(inputPts, inputTangs);
  }
  { ObjFile obj("demo3_output.obj"); obj.group("result_curve"); obj.writeCurve(curve); }
  { ObjFile obj("demo3_ctrl.obj");   obj.writeCtrlPoly(curve); }
  std::cout << "  -> demo3_input.obj, demo3_output.obj, demo3_ctrl.obj\n";
}

// ===========================================================================
// Demo 4: Surface interpolation through a grid of (UV, XYZ) data
// ===========================================================================
static void Demo4_SurfInterpPoints()
{
  const int Nu = 6, Nv = 6;
  NCollection_Array2<gp_Pnt> grid(1, Nu, 1, Nv);
  std::vector<gp_Pnt> gridPts;

  for (int i = 1; i <= Nu; ++i) {
    double u = (i - 1) * M_PI / (Nu - 1);
    for (int j = 1; j <= Nv; ++j) {
      double v = (j - 1) * M_PI / (Nv - 1);
      gp_Pnt p(u, v, std::sin(u) * std::cos(v));
      grid(i, j) = p;
      gridPts.push_back(p);
    }
  }

  GeomAPI_PointsToBSplineSurface fitter;
  fitter.Interpolate(grid);

  occ::handle<Geom_BSplineSurface> surf = fitter.Surface();
  PrintSurfaceInfo(surf, "Demo4 (grid point interp)");

  if (!surf.IsNull()) {
    gp_Pnt evalPt;
    double umid = (surf->UKnot(1) + surf->UKnot(surf->NbUKnots())) * 0.5;
    double vmid = (surf->VKnot(1) + surf->VKnot(surf->NbVKnots())) * 0.5;
    surf->D0(umid, vmid, evalPt);
    std::cout << "  Sample at (umid,vmid): ("
              << evalPt.X() << ", " << evalPt.Y() << ", " << evalPt.Z() << ")\n";
  }

  { ObjFile obj("demo4_input.obj");  obj.group("grid_points");   obj.writePoints(gridPts); }
  { ObjFile obj("demo4_output.obj"); obj.group("result_surface"); obj.writeSurface(surf, 30, 30); }
  { ObjFile obj("demo4_ctrl.obj");   obj.writeCtrlNet(surf); }
  std::cout << "  -> demo4_input.obj, demo4_output.obj, demo4_ctrl.obj\n";
}

// ===========================================================================
// main
// ===========================================================================
int main()
{
  std::cout << "=== OCCT Interpolation Demos ===\n\n";

  std::cout << "--- Demo 1: Curve interp (points only) ---\n";
  Demo1_CurveInterpPoints();

  std::cout << "\n--- Demo 2: Curve interp (end tangents) ---\n";
  Demo2_CurveInterpEndTangents();

  std::cout << "\n--- Demo 3: Curve interp (per-point tangents) ---\n";
  Demo3_CurveInterpAllTangents();

  std::cout << "\n--- Demo 4: Surface interp (point grid) ---\n";
  Demo4_SurfInterpPoints();

  std::cout << "\nDone.\n";
  return 0;
}
