// DemoApprox.cxx
// Demonstrates 4 approximation (rebuild/fitting) use-cases using OCCT.
// Each demo writes input and result to separate OBJ files for visualization.
//
// Demos:
//   5. Single curve rebuild (sample D0 + D1 tangent + D2 curvature)
//   6. Curve chain rebuild (multiple segments, matching at joints)
//   7. Single curve rebuild with prescribed discontinuity parameters
//   8. Surface rebuild (sample D0 + first/second derivatives)

#include <Approx_Curve3d.hxx>
#include <Geom_BSplineCurve.hxx>
#include <GeomAdaptor_Curve.hxx>
#include <Geom_Circle.hxx>
#include <Geom_BezierCurve.hxx>
#include <Geom_TrimmedCurve.hxx>

#include <AdvApprox_ApproxAFunction.hxx>
#include <AdvApprox_DichoCutting.hxx>
#include <AdvApprox_PrefAndRec.hxx>
#include <AdvApprox_EvaluatorFunction.hxx>

#include <AdvApp2Var_ApproxAFunc2Var.hxx>
#include <AdvApp2Var_EvaluatorFunc2Var.hxx>
#include <AdvApprox_Cutting.hxx>

#include <GeomAbs_Shape.hxx>
#include <GeomAbs_IsoType.hxx>
#include <NCollection_Array1.hxx>
#include <NCollection_HArray1.hxx>
#include <NCollection_HArray2.hxx>
#include <Geom_BSplineSurface.hxx>
#include <gp_Pnt.hxx>
#include <gp_Vec.hxx>
#include <gp_Ax2.hxx>
#include <gp_Circ.hxx>
#include <cmath>
#include <iostream>
#include <fstream>
#include <vector>
#include <string>
#include <functional>

// ===========================================================================
// OBJ output helpers
// ===========================================================================

struct ObjFile {
  std::ofstream f;
  int vcount = 0;

  ObjFile(const std::string& path) : f(path) {
    f << "# Generated by DemoApprox\n";
  }
  ~ObjFile() { f.close(); }

  void group(const char* name) { f << "g " << name << "\n"; }

  int vertex(const gp_Pnt& p) {
    f << "v " << p.X() << " " << p.Y() << " " << p.Z() << "\n";
    return ++vcount;
  }

  // Write a polyline as consecutive 2-vertex line segments
  void writePolyline(const std::vector<gp_Pnt>& pts) {
    if (pts.size() < 2) return;
    int base = vcount;
    for (auto& p : pts) vertex(p);
    for (int i = 0; i < (int)pts.size() - 1; ++i)
      f << "l " << (base + i + 1) << " " << (base + i + 2) << "\n";
  }

  // Write BSpline curve control points and control polygon
  void writeCtrlPoly(const occ::handle<Geom_BSplineCurve>& C) {
    if (C.IsNull()) return;
    int nP = C->NbPoles();
    group("ctrl_points");
    int base = vcount;
    for (int i = 1; i <= nP; ++i) vertex(C->Pole(i));
    for (int i = 0; i < nP; ++i)
      f << "p " << (base + i + 1) << "\n";
    group("ctrl_polygon");
    for (int i = 0; i < nP - 1; ++i)
      f << "l " << (base + i + 1) << " " << (base + i + 2) << "\n";
  }

  // Write BSpline surface control points and control net
  void writeCtrlNet(const occ::handle<Geom_BSplineSurface>& S) {
    if (S.IsNull()) return;
    int nU = S->NbUPoles(), nV = S->NbVPoles();
    group("ctrl_points");
    int base = vcount;
    for (int i = 1; i <= nU; ++i)
      for (int j = 1; j <= nV; ++j)
        vertex(S->Pole(i, j));
    for (int i = 0; i < nU * nV; ++i)
      f << "p " << (base + i + 1) << "\n";
    group("ctrl_net_u");
    for (int i = 0; i < nU; ++i)
      for (int j = 0; j < nV - 1; ++j) {
        int v0 = base + i * nV + j + 1;
        f << "l " << v0 << " " << (v0 + 1) << "\n";
      }
    group("ctrl_net_v");
    for (int j = 0; j < nV; ++j)
      for (int i = 0; i < nU - 1; ++i) {
        int v0 = base + i * nV + j + 1;
        int v1 = base + (i + 1) * nV + j + 1;
        f << "l " << v0 << " " << v1 << "\n";
      }
  }

  // Sample a parametric function and write as polyline
  void writeFunc(const std::function<gp_Pnt(double)>& func,
                 double t0, double t1, int nSamples = 200) {
    std::vector<gp_Pnt> pts;
    for (int i = 0; i <= nSamples; ++i) {
      double t = t0 + (t1 - t0) * i / nSamples;
      pts.push_back(func(t));
    }
    writePolyline(pts);
  }

  // Sample a BSpline curve and write as polyline
  void writeCurve(const occ::handle<Geom_BSplineCurve>& C, int nSamples = 200) {
    if (C.IsNull()) return;
    double u0 = C->FirstParameter(), u1 = C->LastParameter();
    writeFunc([&](double u) { gp_Pnt p; C->D0(u, p); return p; },
              u0, u1, nSamples);
  }

  // Sample a parametric surface function and write as triangle mesh
  void writeFuncSurf(const std::function<gp_Pnt(double, double)>& func,
                     double u0, double u1, double v0, double v1,
                     int nu = 40, int nv = 40) {
    int base = vcount;
    for (int i = 0; i <= nu; ++i) {
      double u = u0 + (u1 - u0) * i / nu;
      for (int j = 0; j <= nv; ++j) {
        double v = v0 + (v1 - v0) * j / nv;
        vertex(func(u, v));
      }
    }
    for (int i = 0; i < nu; ++i) {
      for (int j = 0; j < nv; ++j) {
        int v00 = base + i * (nv + 1) + j + 1;
        int v10 = base + (i + 1) * (nv + 1) + j + 1;
        int v01 = v00 + 1;
        int v11 = v10 + 1;
        f << "f " << v00 << " " << v10 << " " << v11 << "\n";
        f << "f " << v00 << " " << v11 << " " << v01 << "\n";
      }
    }
  }

  // Sample a BSpline surface and write as triangle mesh
  void writeSurface(const occ::handle<Geom_BSplineSurface>& S,
                    int nu = 40, int nv = 40) {
    if (S.IsNull()) return;
    double u0 = S->UKnot(1), u1 = S->UKnot(S->NbUKnots());
    double v0 = S->VKnot(1), v1 = S->VKnot(S->NbVKnots());
    writeFuncSurf([&](double u, double v) {
      gp_Pnt p; S->D0(u, v, p); return p;
    }, u0, u1, v0, v1, nu, nv);
  }
};

// ---------------------------------------------------------------------------
// Helper
// ---------------------------------------------------------------------------
static void PrintCurveInfo(const occ::handle<Geom_BSplineCurve>& C, const char* label)
{
  if (C.IsNull()) { std::cout << label << ": FAILED\n"; return; }
  std::cout << label
            << ": degree=" << C->Degree()
            << "  nbPoles=" << C->NbPoles()
            << "  nbKnots=" << C->NbKnots() << "\n";
}

// ===========================================================================
// Demo 5: Single curve rebuild
// ===========================================================================

class HelixAdaptor : public Adaptor3d_Curve
{
public:
  HelixAdaptor(double R, double H, double t0, double t1)
    : myR(R), myH(H), myT0(t0), myT1(t1) {}

  double FirstParameter() const override { return myT0; }
  double LastParameter()  const override { return myT1; }

  void D0(const double t, gp_Pnt& P) const override {
    P.SetCoord(myR * std::cos(t), myR * std::sin(t), myH * t / (2.0 * M_PI));
  }
  void D1(const double t, gp_Pnt& P, gp_Vec& V) const override {
    D0(t, P);
    V.SetCoord(-myR * std::sin(t), myR * std::cos(t), myH / (2.0 * M_PI));
  }
  void D2(const double t, gp_Pnt& P, gp_Vec& V1, gp_Vec& V2) const override {
    D1(t, P, V1);
    V2.SetCoord(-myR * std::cos(t), -myR * std::sin(t), 0.0);
  }

  GeomAbs_Shape Continuity() const override { return GeomAbs_CN; }
  GeomAbs_CurveType GetType() const override { return GeomAbs_OtherCurve; }
  gp_Lin Line() const override { return gp_Lin(); }
  gp_Circ Circle() const override { return gp_Circ(); }
  gp_Elips Ellipse() const override { return gp_Elips(); }
  gp_Hypr Hyperbola() const override { return gp_Hypr(); }
  gp_Parab Parabola() const override { return gp_Parab(); }
  int Degree() const override { return 3; }
  bool IsRational() const override { return false; }
  bool IsPeriodic() const override { return false; }
  double Period() const override { return 2.0 * M_PI; }
  int NbPoles() const override { return 0; }
  int NbKnots() const override { return 0; }
  occ::handle<Geom_BezierCurve> Bezier() const override { return {}; }
  occ::handle<Geom_BSplineCurve> BSpline() const override { return {}; }
  occ::handle<Geom_OffsetCurve> OffsetCurve() const override { return {}; }
  int NbIntervals(const GeomAbs_Shape) const override { return 1; }
  void Intervals(NCollection_Array1<double>& T, const GeomAbs_Shape) const override {
    T(T.Lower()) = myT0; T(T.Upper()) = myT1;
  }
  occ::handle<Adaptor3d_Curve> Trim(double f, double l, double) const override {
    return new HelixAdaptor(myR, myH, f, l);
  }
  gp_Vec DN(const double t, const int N) const override {
    gp_Pnt P; gp_Vec V1, V2;
    if (N == 1) { D1(t,P,V1); return V1; }
    if (N == 2) { D2(t,P,V1,V2); return V2; }
    return gp_Vec();
  }
  gp_Pnt Value(const double t) const override { gp_Pnt P; D0(t,P); return P; }

private:
  double myR, myH, myT0, myT1;
};

static void Demo5_SingleCurveRebuild()
{
  occ::handle<HelixAdaptor> helix = new HelixAdaptor(1.0, 1.0, 0.0, 2.0 * M_PI);

  Approx_Curve3d rebuilder(helix,
                           /*Tol3d=*/1.0e-4,
                           /*Order=*/GeomAbs_C2,
                           /*MaxSeg=*/20,
                           /*MaxDeg=*/9);

  occ::handle<Geom_BSplineCurve> result;
  if (rebuilder.IsDone()) {
    result = rebuilder.Curve();
    PrintCurveInfo(result, "Demo5 (single curve rebuild C2)");
  } else {
    std::cout << "Demo5: HasResult=" << rebuilder.HasResult()
              << "  MaxError=" << rebuilder.MaxError() << "\n";
  }
  std::cout << "  MaxError=" << rebuilder.MaxError() << "\n";

  {
    ObjFile obj("demo5_input.obj");
    obj.group("helix");
    obj.writeFunc([&](double t) { return helix->Value(t); }, 0.0, 2.0 * M_PI);
  }
  {
    ObjFile obj("demo5_output.obj");
    obj.group("result_curve");
    obj.writeCurve(result);
  }
  { ObjFile obj("demo5_ctrl.obj"); obj.writeCtrlPoly(result); }
  std::cout << "  -> demo5_input.obj, demo5_output.obj, demo5_ctrl.obj\n";
}

// ===========================================================================
// Demo 6: Curve chain rebuild
// ===========================================================================
static void Demo6_CurveChainRebuild()
{
  struct ArcDef { gp_Ax2 ax; double r; double t0; double t1; };
  std::vector<ArcDef> arcs = {
    { gp_Ax2(gp_Pnt(0,0,0), gp_Dir(0,0,1)), 1.0, 0.0,    M_PI/2.0 },
    { gp_Ax2(gp_Pnt(1,1,0), gp_Dir(1,0,0)), 1.0, -M_PI/2.0, 0.0  },
    { gp_Ax2(gp_Pnt(1,0,1), gp_Dir(0,1,0)), 1.0, 0.0,    M_PI/2.0 },
  };

  ObjFile objIn("demo6_input.obj");
  ObjFile objOut("demo6_output.obj");
  ObjFile objCtrl("demo6_ctrl.obj");

  for (int k = 0; k < (int)arcs.size(); ++k) {
    occ::handle<Geom_Circle> circ = new Geom_Circle(gp_Circ(arcs[k].ax, arcs[k].r));
    occ::handle<Geom_TrimmedCurve> arc = new Geom_TrimmedCurve(circ, arcs[k].t0, arcs[k].t1);
    occ::handle<GeomAdaptor_Curve> hAdaptor = new GeomAdaptor_Curve(arc);

    Approx_Curve3d rebuilder(hAdaptor,
                             /*Tol3d=*/1.0e-5,
                             /*Order=*/GeomAbs_C1,
                             /*MaxSeg=*/10,
                             /*MaxDeg=*/7);

    char label[64], grp[64];
    std::snprintf(label, sizeof(label), "Demo6 segment %d", k + 1);

    std::snprintf(grp, sizeof(grp), "arc_%d", k + 1);
    objIn.group(grp);
    objIn.writeFunc([&](double t) { gp_Pnt p; arc->D0(t, p); return p; },
                    arcs[k].t0, arcs[k].t1, 50);

    if (rebuilder.IsDone()) {
      PrintCurveInfo(rebuilder.Curve(), label);
      std::snprintf(grp, sizeof(grp), "curve_%d", k + 1);
      objOut.group(grp);
      objOut.writeCurve(rebuilder.Curve(), 50);
      objCtrl.writeCtrlPoly(rebuilder.Curve());
    } else {
      std::cout << label << ": partial, maxErr=" << rebuilder.MaxError() << "\n";
    }
  }
  std::cout << "  -> demo6_input.obj, demo6_output.obj, demo6_ctrl.obj\n";
}

// ===========================================================================
// Demo 7: Single curve rebuild with discontinuity parameters
// ===========================================================================

static void KinkCurveD0(double t, double result[3])
{
  if (t <= M_PI) {
    result[0] = std::cos(t);
    result[1] = std::sin(t);
    result[2] = 0.0;
  } else {
    result[0] = std::cos(t);
    result[1] = -std::sin(t) + 2.0;
    result[2] = 0.5;
  }
}

class KinkCurveEvaluator : public AdvApprox_EvaluatorFunction
{
public:
  void Evaluate(int*    /*Dimension*/,
                double  /*StartEnd*/[2],
                double* Parameter,
                int*    DerivativeRequest,
                double* Result,
                int*    ErrorCode) override
  {
    double t  = *Parameter;
    int    d  = *DerivativeRequest;
    *ErrorCode = 0;

    double h = 1.0e-6;
    if (d == 0) {
      KinkCurveD0(t, Result);
    } else if (d == 1) {
      double r0[3], r1[3];
      KinkCurveD0(t - h, r0); KinkCurveD0(t + h, r1);
      for (int i = 0; i < 3; ++i) Result[i] = (r1[i] - r0[i]) / (2.0 * h);
    } else if (d == 2) {
      double r0[3], r1[3], r2[3];
      KinkCurveD0(t - h, r0); KinkCurveD0(t, r1); KinkCurveD0(t + h, r2);
      for (int i = 0; i < 3; ++i) Result[i] = (r0[i] - 2*r1[i] + r2[i]) / (h*h);
    }
  }
};

static void Demo7_CurveRebuildWithDiscontinuity()
{
  NCollection_Array1<double> pref(1, 1);  pref(1) = M_PI;
  NCollection_Array1<double> rec (1, 3);
  rec(1) = M_PI / 2.0;
  rec(2) = M_PI;
  rec(3) = 3.0 * M_PI / 2.0;

  AdvApprox_PrefAndRec cutter(pref, rec);
  KinkCurveEvaluator   evaluator;

  occ::handle<NCollection_HArray1<double>> tol1d = new NCollection_HArray1<double>(1,0);
  occ::handle<NCollection_HArray1<double>> tol2d = new NCollection_HArray1<double>(1,0);
  occ::handle<NCollection_HArray1<double>> tol3d = new NCollection_HArray1<double>(1,1);
  tol3d->SetValue(1, 1.0e-4);

  AdvApprox_ApproxAFunction approx(
    /*Num1D=*/0, /*Num2D=*/0, /*Num3D=*/1,
    tol1d, tol2d, tol3d,
    /*First=*/0.0, /*Last=*/2.0 * M_PI,
    /*Cont=*/GeomAbs_C0,
    /*MaxDeg=*/9,
    /*MaxSeg=*/20,
    evaluator, cutter);

  // Write input
  {
    ObjFile obj("demo7_input.obj");
    obj.group("kink_curve");
    obj.writeFunc([](double t) {
      double r[3]; KinkCurveD0(t, r);
      return gp_Pnt(r[0], r[1], r[2]);
    }, 0.0, 2.0 * M_PI);
  }

  if (approx.IsDone()) {
    std::cout << "Demo7 (kink curve rebuild):"
              << "  degree=" << approx.Degree()
              << "  nbKnots=" << approx.NbKnots()
              << "  maxErr=" << approx.MaxError(3, 1) << "\n";
    auto knots = approx.Knots();
    bool foundKink = false;
    for (int i = knots->Lower(); i <= knots->Upper(); ++i) {
      if (std::fabs(knots->Value(i) - M_PI) < 1.0e-8) { foundKink = true; break; }
    }
    std::cout << "  kink knot at pi found: " << (foundKink ? "YES" : "NO") << "\n";

    // Build BSpline curve from AdvApprox result
    auto poles3d = approx.Poles();
    auto knotsArr = approx.Knots();
    auto mults = approx.Multiplicities();
    int deg = approx.Degree();

    NCollection_Array1<gp_Pnt> bsPoles(1, poles3d->ColLength());
    for (int i = 1; i <= poles3d->ColLength(); ++i)
      bsPoles(i) = poles3d->Value(i, 1);

    NCollection_Array1<double> bsKnots(knotsArr->Lower(), knotsArr->Upper());
    for (int i = knotsArr->Lower(); i <= knotsArr->Upper(); ++i)
      bsKnots(i) = knotsArr->Value(i);

    NCollection_Array1<int> bsMults(mults->Lower(), mults->Upper());
    for (int i = mults->Lower(); i <= mults->Upper(); ++i)
      bsMults(i) = mults->Value(i);

    occ::handle<Geom_BSplineCurve> resultCurve =
      new Geom_BSplineCurve(bsPoles, bsKnots, bsMults, deg);

    ObjFile obj("demo7_output.obj");
    obj.group("result_curve");
    obj.writeCurve(resultCurve);

    ObjFile objCtrl("demo7_ctrl.obj");
    objCtrl.writeCtrlPoly(resultCurve);
  } else {
    std::cout << "Demo7: HasResult=" << approx.HasResult() << "\n";
  }
  std::cout << "  -> demo7_input.obj, demo7_output.obj, demo7_ctrl.obj\n";
}

// ===========================================================================
// Demo 8: Surface rebuild via AdvApp2Var
// ===========================================================================

static gp_Pnt TorusD0(double u, double v)
{
  const double R = 2.0, r = 0.5;
  double rho = R + r * std::cos(v);
  return gp_Pnt(rho * std::cos(u), rho * std::sin(u), r * std::sin(v));
}

class TorusEvaluator : public AdvApp2Var_EvaluatorFunc2Var
{
public:
  void Evaluate(int*    theDimension,
                double* /*theUStartEnd*/,
                double* /*theVStartEnd*/,
                int*    theFavorIso,
                double* theConstParam,
                int*    theNbParams,
                double* theParameters,
                int*    theUOrder,
                int*    theVOrder,
                double* theResult,
                int*    theErrorCode) const override
  {
    const double R = 2.0, radius = 0.5;
    int dim = *theDimension;
    int N   = *theNbParams;
    int ou  = *theUOrder;
    int ov  = *theVOrder;
    *theErrorCode = 0;

    for (int ip = 0; ip < N; ++ip) {
      double u, v;
      if (*theFavorIso == 1) {
        u = *theConstParam;
        v = theParameters[ip];
      } else {
        u = theParameters[ip];
        v = *theConstParam;
      }

      double* res = theResult + ip * dim;
      double rho = R + radius * std::cos(v);

      if (ou == 0 && ov == 0) {
        res[0] = rho * std::cos(u);
        res[1] = rho * std::sin(u);
        res[2] = radius * std::sin(v);
      }
      else if (ou == 1 && ov == 0) {
        res[0] = -rho * std::sin(u);
        res[1] =  rho * std::cos(u);
        res[2] =  0.0;
      }
      else if (ou == 0 && ov == 1) {
        double drho = -radius * std::sin(v);
        res[0] = drho * std::cos(u);
        res[1] = drho * std::sin(u);
        res[2] = radius * std::cos(v);
      }
      else if (ou == 2 && ov == 0) {
        res[0] = -rho * std::cos(u);
        res[1] = -rho * std::sin(u);
        res[2] =  0.0;
      }
      else if (ou == 0 && ov == 2) {
        double d2rho = -radius * std::cos(v);
        res[0] = d2rho * std::cos(u);
        res[1] = d2rho * std::sin(u);
        res[2] = -radius * std::sin(v);
      }
      else if (ou == 1 && ov == 1) {
        double drho = -radius * std::sin(v);
        res[0] = -drho * std::sin(u);
        res[1] =  drho * std::cos(u);
        res[2] =  0.0;
      }
      else {
        *theErrorCode = 1;
        return;
      }
    }
  }
};

static void Demo8_SurfaceRebuild()
{
  occ::handle<NCollection_HArray1<double>> tol1d = new NCollection_HArray1<double>(1,0);
  occ::handle<NCollection_HArray1<double>> tol2d = new NCollection_HArray1<double>(1,0);
  occ::handle<NCollection_HArray1<double>> tol3d = new NCollection_HArray1<double>(1,1);
  tol3d->SetValue(1, 1.0e-4);

  occ::handle<NCollection_HArray2<double>> btol1d = new NCollection_HArray2<double>(1,1,1,4);
  occ::handle<NCollection_HArray2<double>> btol2d = new NCollection_HArray2<double>(1,1,1,4);
  occ::handle<NCollection_HArray2<double>> btol3d = new NCollection_HArray2<double>(1,1,1,4);
  for (int i = 1; i <= 4; ++i) btol3d->SetValue(1, i, 1.0e-4);

  TorusEvaluator    evaluator;
  AdvApprox_DichoCutting ucutter, vcutter;

  double u0 = 0.0, u1 = M_PI / 2.0;
  double v0 = 0.0, v1 = M_PI / 2.0;

  AdvApp2Var_ApproxAFunc2Var approx(
    /*Num1D=*/0, /*Num2D=*/0, /*Num3D=*/1,
    tol1d, tol2d, tol3d,
    btol1d, btol2d, btol3d,
    u0, u1, v0, v1,
    /*FavorIso=*/GeomAbs_IsoV,
    /*ContU=*/GeomAbs_C1,
    /*ContV=*/GeomAbs_C1,
    /*PrecisCode=*/2,
    /*MaxDegU=*/9,
    /*MaxDegV=*/9,
    /*MaxPatch=*/16,
    evaluator, ucutter, vcutter);

  // Write input torus patch
  {
    ObjFile obj("demo8_input.obj");
    obj.group("torus");
    obj.writeFuncSurf([](double u, double v) { return TorusD0(u, v); },
                      u0, u1, v0, v1, 30, 30);
  }

  if (approx.IsDone()) {
    occ::handle<Geom_BSplineSurface> surf =
      occ::handle<Geom_BSplineSurface>::DownCast(approx.Surface(1));
    if (!surf.IsNull()) {
      std::cout << "Demo8 (torus patch rebuild):"
                << "  degU=" << surf->UDegree()
                << "  degV=" << surf->VDegree()
                << "  nPolesU=" << surf->NbUPoles()
                << "  nPolesV=" << surf->NbVPoles() << "\n";

      ObjFile obj("demo8_output.obj");
      obj.group("result_surface");
      obj.writeSurface(surf, 30, 30);

      ObjFile objCtrl("demo8_ctrl.obj");
      objCtrl.writeCtrlNet(surf);
    }
    std::cout << "  maxErr3D=" << approx.MaxError(3, 1) << "\n";
    std::cout << "  avgErr3D=" << approx.AverageError(3, 1) << "\n";
  } else {
    std::cout << "Demo8: HasResult=" << approx.HasResult() << "\n";
  }
  std::cout << "  -> demo8_input.obj, demo8_output.obj, demo8_ctrl.obj\n";
}

// ===========================================================================
// main
// ===========================================================================
int main()
{
  std::cout << "=== OCCT Approximation (Rebuild) Demos ===\n\n";

  std::cout << "--- Demo 5: Single curve rebuild (D0+D1+D2, C2) ---\n";
  Demo5_SingleCurveRebuild();

  std::cout << "\n--- Demo 6: Curve chain rebuild (3 arcs, C1 each) ---\n";
  Demo6_CurveChainRebuild();

  std::cout << "\n--- Demo 7: Curve rebuild with discontinuity at pi ---\n";
  Demo7_CurveRebuildWithDiscontinuity();

  std::cout << "\n--- Demo 8: Surface rebuild (torus patch, C1 x C1) ---\n";
  Demo8_SurfaceRebuild();

  std::cout << "\nDone.\n";
  return 0;
}
